info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/answer/{id}:
    patch:
      operationId: answer_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this answer.
          title: ID
          type: integer
      tags:
      - answer
    put:
      operationId: answer_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this answer.
          title: ID
          type: integer
      tags:
      - answer
  /api/poll:
    get:
      operationId: poll_list
      tags:
      - poll
    post:
      operationId: poll_create
      tags:
      - poll
  /api/poll/{id}:
    delete:
      operationId: poll_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this poll.
          title: ID
          type: integer
      tags:
      - poll
    get:
      operationId: poll_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this poll.
          title: ID
          type: integer
      tags:
      - poll
    patch:
      operationId: poll_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this poll.
          title: ID
          type: integer
      tags:
      - poll
    put:
      operationId: poll_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this poll.
          title: ID
          type: integer
      tags:
      - poll
  /api/questions:
    get:
      operationId: questions_list
      tags:
      - questions
    post:
      operationId: questions_create
      tags:
      - questions
  /api/questions/{id}:
    delete:
      operationId: questions_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this question.
          title: ID
          type: integer
      tags:
      - questions
    get:
      operationId: questions_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this question.
          title: ID
          type: integer
      tags:
      - questions
    patch:
      operationId: questions_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this question.
          title: ID
          type: integer
      tags:
      - questions
    put:
      operationId: questions_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this question.
          title: ID
          type: integer
      tags:
      - questions
  /api/report/{id}:
    delete:
      operationId: report_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this report.
          title: ID
          type: integer
      tags:
      - report
    get:
      operationId: report_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this report.
          title: ID
          type: integer
      tags:
      - report
    patch:
      operationId: report_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this report.
          title: ID
          type: integer
      tags:
      - report
    put:
      operationId: report_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this report.
          title: ID
          type: integer
      tags:
      - report
servers:
- url: ''
