# Generated by Django 3.2.7 on 2021-09-22 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0003_auto_20210922_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='poll.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
