# Generated by Django 3.2.7 on 2021-09-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0004_auto_20210922_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='poll_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='poll.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
