# Generated by Django 3.2.7 on 2021-09-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210922_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='poll_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
    ]
