# Generated by Django 3.2.7 on 2021-09-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20210922_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='poll_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
    ]
