# Generated by Django 3.2.7 on 2021-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_question_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
