# Generated by Django 3.2.7 on 2021-09-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_alter_answer_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
