# Generated by Django 3.2.7 on 2021-09-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_choice',
            name='question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chooses', to='poll.question'),
        ),
    ]
